name: scentlab
channels:
  - conda-forge
dependencies:
  - python=3.10
  - rdkit=2022.09.*
  - numpy=1.24.4
  - pandas>=1.5,<2.3
  - pyarrow>=10,<15
  - networkx=3.4.2
  - fastparquet
  - scikit-learn>=1.2,<1.5
  - imbalanced-learn=0.11.*
  - xgboost>=2.0
  - matplotlib
  - seaborn
  - openpyxl
  - tqdm
  - ipykernel
  - ipywidgets=8
  - jupyterlab_widgets
  - pip
  - pip:
      - pyrfume>=0.19.1
      - mordredcommunity>=2.0.6
      - sentence-transformers>=2.7.0
      - torch>=2.3.0
